#!/usr/bin/env ruby

require 'sqlite3'
require 'net/http'
require 'json'
require "base64"

begin
  file_name = File.dirname(__FILE__) + '/../data/chrome.tmp'

  puts 'Expiring all existing entries...'
  db = SQLite3::Database.open File.dirname(__FILE__) + '/../data/preload_status.db'
  db.execute "update chrome set status = 0, last_update = #{Time.now.to_i}"

  puts 'Downloading Chrome Preload list...'
  File.write(file_name, Net::HTTP.get(URI.parse('https://chromium.googlesource.com/chromium/src/net/+/master/http/transport_security_state_static.json?format=TEXT')))

  puts 'Parsing result...'
  raw = Base64.decode64 File.read(file_name)
  data = JSON.parse raw

  puts "Processing #{data['entries'].count} rows..."
  data['entries'].each do |row|
    domain = row['name']

    if row['include_subdomains']
      include_subdomains = 1
    else
      include_subdomains = 0
    end

    db.execute('insert or replace into chrome (domain, status, include_subdomains, last_update) values (:domain, :status, :include_subdomains, :last_update)',
               'domain' => domain,
               'status' => 1,
               'include_subdomains' => include_subdomains,
               'last_update' => Time.now.to_i)
  end

  puts 'Deleting expired records...'
  db.execute 'delete from chrome where status = 0'

  puts 'Done.'
rescue => e
  puts "ERROR: Failed to load new data into database: '#{e.message}'"
ensure
  db.close if db
  File.delete file_name
end
